[package]
name = "7n7o/roblox-project-template"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Maid = "blestooo/maid@0.1.1"