name: Build
on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Name of the uploaded artifact"
        value: ${{ jobs.build.outputs.artifact-name }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifact-name: build-output

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rojo
        run: |
          url=$(curl -s https://api.github.com/repos/rojo-rbx/rojo/releases/latest \
            | grep browser_download_url \
            | grep linux-x86_64 \
            | cut -d '"' -f 4)

          curl -L "$url" -o rojo.zip
          unzip rojo.zip
          chmod +x rojo
          sudo mv rojo /usr/local/bin/

      - name: Install Rust and Cargo
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Cache Cargo registry and builds
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            ~/.cargo/target
          key: cargo-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-cache-${{ runner.os }}-

      - name: Install Darklua via Cargo
        run: |
          source $HOME/.cargo/env
          if ! command -v darklua >/dev/null 2>&1; then
            cargo install --git https://github.com/Stefanuk12/darklua --branch hybrid-mode darklua
          else
            echo "darklua already installed, skipping..."
          fi

      - name: Install Wally
        run: |
          url=$(curl -s https://api.github.com/repos/UpliftGames/wally/releases/latest \
            | grep browser_download_url \
            | grep linux \
            | cut -d '"' -f 4)

          curl -L "$url" -o wally.zip
          unzip wally.zip
          chmod +x wally
          sudo mv wally /usr/local/bin/

      - name: Install wally dependencies
        run: |
          chmod +x wally_install.sh
          ./wally_install.sh

      - name: Run build script
        run: |
          mkdir build
          chmod +x build.sh
          ./build.sh

      - name: Run bundle script
        run: |
          chmod +x bundle.sh
          ./bundle.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/